### ISSUE TITLE
US12 - Eu, como interessado, desejo filtrar os animais a serem doados por espécie, para ver apenas a espécie que eu desejo adotar.

### ISSUE THREAD

**Issue by MacSoares** [ludimila/TrabalhoDAS#12]

**Comment by Ziul** [comment]
**Guia de Referencia:** [has_scope](https://github.com/plataformatec/has_scope)

Filtre usando algo como:

    http://0.0.0.0:3000/animals?by_breed=India

* Não é _case sesitive_
* Filtros inexistentes são ignorados
