### ISSUE TITLE
US14 - Eu como usuário desejo ser notificado (via email) quando uma pessoa tiver interesse em um animal meu.

### ISSUE THREAD

**Issue by ludimila** [ludimila/TrabalhoDAS#15]
No momento em que um usuário fica interessado em um animal setado para doação, um email será disparado para o doador

**Comment by MacSoares** [comment]
A priori, o sistema de envio de emails será feito para envio de emails genéricos, e com o avanço do sistema, o email notificará o interesse num animal.

**Comment by MacSoares** [comment]
Fluxo inicial de envio de emails no momento do compartilhamento de um novo animal já está funcional. Para finalizar a US, é necessário implementar envio de emails quando usuario demonstrar interesse

**Comment by MacSoares** [comment]
O escopo final da US-14 foi envio de emails no momento do cadastro do usuário e quando ele adiciona um novo pet no sistema
