### ISSUE TITLE
US15 - Eu como doador, desejo me logar no sistema por meio da minha conta do twitter.

### ISSUE THREAD

**Issue by ludimila** [ludimila/TrabalhoDAS#16]

**Comment by caiquepereira** [comment]
Quais informacoes o twitter fornece via login?

**Comment by caiquepereira** [comment]
Consumer Key (API Key)	CjnwzLIJ9M8fuag7rjtghPuvM
Consumer Secret (API Secret)	qj4X7A373kguT6gJtoi2kIqBtZ0xDWS6WPxvEPQUAvkjGT08nZ

**Comment by caiquepereira** [comment]
Continuar video a partir de 4mins

**Comment by caiquepereira** [comment]
killall -9 rails
